/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UserInterfaceTesting.Framework.Puma;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
